apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qopy7zz9s-python 
  janus-idp.io/tekton: qopy7zz9s-python
  backstage.io/kubernetes-id: qopy7zz9s-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qopy7zz9s-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml